title: CS 188 Study Group
description: Collaborative resources for Intro to AI at CAU.
theme: jekyll-theme-minimal # A clean, fast-loading default

# Navigation Links
header_pages:
  - index.md
  - syllabus.md
  - resources.md

# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme