title: CS 188 Study Group
description: Collaborative resources for Intro to AI at CAU.
theme: jekyll-theme-cayman

# Navigation Links (Cayman displays these as buttons in the header)
header_pages:
  - index.md
  - syllabus.md
  - resources.md